### ISSUE TITLE
BlackMagicURLProvider.py uses deprecated urllib2, broken when using autopkg 2.0.2

### ISSUE THREAD

**Issue by modestindustries** [autopkg/timsutton-recipes#76]
I believe that this is due to urllib2 being deprecated in Python3, included in autopkg 2.0.2. 

The specific error is:

WARNING: /Volumes/AutoPKG Data/Autopkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Blackmagic/BlackMagicURLProvider.py: No module named 'urllib2'
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/AutoPKG Data/Autopkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Blackmagic/BlackMagicURLProvider.py", line 22, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.

**Comment by timsutton** [comment]
This should now be fixed in #80, thanks also to @bochoven in #65.
